<?php

return [
    'itemsPorPagina' => 10,
    'precio_mensual_por_empresa_mxn' => 150,
    'tasa_iva' => 16,
    'video_como_funciona_youtube' => 'https://youtu.be/TdkJnSW34to',
    'aniosAsistencia' => [2026, 2027],
    'emisor' => [
        'rfc' => 'SAOJ750515T19',
        'razon_social' => 'JUAN CARLOS SALINAS OJEDA',
        'calle' => '3ra. Privada Vicente Guerrero ',
        'interior' => '12',
        'colonia' => 'San Francisco Culhuacan La Magdalena',
        'alcaldia' => 'Coyoacán',
        'ciudad' => 'CDMX',
        'codigo_postal' => '04260',
        'regimen_clave' => '612',
        'regimen' => '612 — Personas Físicas con Actividades Empresariales y Profesionales',
    ],
    'concepto_factura' => [
        'clave_prod_serv' => '81112501',
        'descripcion' => 'SUSCRIPCIÓN MENSUAL HORALIA',
        'clave_unidad' => 'E48',
        'unidad' => 'Unidad de servicio',
        'objeto_impuesto' => '02',
    ],
    'facturacion' => [
        'serie' => 'H',
        'ultimo_folio_inicial' => 1000,
        'tipo_comprobante' => 'I',
        'metodo_pago' => 'PUE',
        'exportacion' => '01',
        'disco_csd' => 'local',
        'directorio_csd' => 'csd',
        'logo_pdf' => 'assets/logos/logoLN.png',
        'qr_graphoria_url' => 'https://graphoria.dev/qr',
        'qr_sat_url' => 'https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx',
    ],
    'perfilesPersonal' => [
        'administrador' => ['id' => 2, 'nombre' => 'Administrador'],
        'empleado_regular' => ['id' => 3, 'nombre' => 'Empleado Regular'],
    ],
    'entidades_federativas' => [
        'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas',
        'Chihuahua', 'Ciudad de México', 'Coahuila de Zaragoza', 'Colima', 'Durango',
        'Estado de México', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Michoacán de Ocampo',
        'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo',
        'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala',
        'Veracruz de Ignacio de la Llave', 'Yucatán', 'Zacatecas',
    ],
    // Catálogo c_RegimenFiscal del Anexo 20, CFDI 4.0.
    'regimenes_fiscales' => [
        '601' => ['descripcion' => 'General de Ley Personas Morales', 'tipo_persona' => 'moral'],
        '603' => ['descripcion' => 'Personas Morales con Fines no Lucrativos', 'tipo_persona' => 'moral'],
        '605' => ['descripcion' => 'Sueldos y Salarios e Ingresos Asimilados a Salarios', 'tipo_persona' => 'fisica'],
        '606' => ['descripcion' => 'Arrendamiento', 'tipo_persona' => 'fisica'],
        '607' => ['descripcion' => 'Régimen de Enajenación o Adquisición de Bienes', 'tipo_persona' => 'fisica'],
        '608' => ['descripcion' => 'Demás ingresos', 'tipo_persona' => 'fisica'],
        '610' => ['descripcion' => 'Residentes en el Extranjero sin Establecimiento Permanente en México', 'tipo_persona' => 'ambas'],
        '611' => ['descripcion' => 'Ingresos por Dividendos (socios y accionistas)', 'tipo_persona' => 'fisica'],
        '612' => ['descripcion' => 'Personas Físicas con Actividades Empresariales y Profesionales', 'tipo_persona' => 'fisica'],
        '614' => ['descripcion' => 'Ingresos por intereses', 'tipo_persona' => 'fisica'],
        '615' => ['descripcion' => 'Régimen de los ingresos por obtención de premios', 'tipo_persona' => 'fisica'],
        '616' => ['descripcion' => 'Sin obligaciones fiscales', 'tipo_persona' => 'fisica'],
        '620' => ['descripcion' => 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos', 'tipo_persona' => 'moral'],
        '621' => ['descripcion' => 'Incorporación Fiscal', 'tipo_persona' => 'fisica'],
        '622' => ['descripcion' => 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras', 'tipo_persona' => 'moral'],
        '623' => ['descripcion' => 'Opcional para Grupos de Sociedades', 'tipo_persona' => 'moral'],
        '624' => ['descripcion' => 'Coordinados', 'tipo_persona' => 'moral'],
        '625' => ['descripcion' => 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', 'tipo_persona' => 'fisica'],
        '626' => ['descripcion' => 'Régimen Simplificado de Confianza', 'tipo_persona' => 'ambas'],
    ],
    // Catálogo c_UsoCFDI del Anexo 20, CFDI 4.0.
    'uso_cfdi' => [
        'G01' => 'Adquisición de mercancías',
        'G02' => 'Devoluciones, descuentos o bonificaciones',
        'G03' => 'Gastos en general',
        'I01' => 'Construcciones',
        'I02' => 'Mobiliario y equipo de oficina por inversiones',
        'I03' => 'Equipo de transporte',
        'I04' => 'Equipo de cómputo y accesorios',
        'I05' => 'Dados, troqueles, moldes, matrices y herramental',
        'I06' => 'Comunicaciones telefónicas',
        'I07' => 'Comunicaciones satelitales',
        'I08' => 'Otra maquinaria y equipo',
        'D01' => 'Honorarios médicos, dentales y gastos hospitalarios',
        'D02' => 'Gastos médicos por incapacidad o discapacidad',
        'D03' => 'Gastos funerales',
        'D04' => 'Donativos',
        'D05' => 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)',
        'D06' => 'Aportaciones voluntarias al SAR',
        'D07' => 'Primas por seguros de gastos médicos',
        'D08' => 'Gastos de transportación escolar obligatoria',
        'D09' => 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones',
        'D10' => 'Pagos por servicios educativos (colegiaturas)',
        'S01' => 'Sin efectos fiscales',
        'CP01' => 'Pagos',
        'CN01' => 'Nómina',
    ],
    'formas_pago_sat' => [
        '04' => 'Tarjeta de crédito',
        '28' => 'Tarjeta de débito',
    ],
];
